/**
    Form.react.js

    @author:
      - Derek Johnston

    @desc:
      - A component container for the <form> element.
*/
import React, { Component } from "react";

class Form extends Component {
  /**
    constructor(props)

    @desc:
      - Create an instance of NewEventsButton

    @param:
      - props (Object): The component's properties passed in by parents.

    @return:
      - An instance of NewEventsButton
  */
  constructor(props) {
    super(props);

    this.handleSubmit = this.handleSubmit.bind(this);
  }

  /**
    render()

    @desc:
      - Draw the component on the screen.

    @param:
      - null

    @return:
      - null
  */
  render() {
    return <form className="form" onSubmit={this.handleSubmit}>
      { this.props.children }
    </form>
  }

  /**
    handleSubmit(event)

    @desc:
      - Negate the default submit functionality and invoke the 'onSubmit'
        property.

    @param:
      - event (Object): The event object automatically generated by the browser.

    @return:
      - null
  */
  handleSubmit(event) {
    event.preventDefault();
    this.props.onSubmit();
  }
}

export default Form;
